from models import Product

MOCK_PRODUCTS: dict[str, list[Product]] = {
    "winter_jackets": [
        Product(
            id="wj-001",
            name="Arctic Explorer Down Parka",
            brand="The North Face",
            price=299.99,
            original_price=349.99,
            shipping_eta="Arrives in 2–3 days",
            rating=4.7,
            review_count=2341,
            value_tag="Best overall",
            description="800-fill goose down parka rated to -30°F with waterproof shell",
            why_recommended="Top-rated warmth and durability — perfect for extreme cold weather",
            source_name="REI",
            source_url="https://www.rei.com/product/arctic-explorer-parka",
            category="winter_jackets",
            available_coupons=1,
            key_features=["800-fill down", "Waterproof", "Rated to -30°F", "Removable hood"],
        ),
        Product(
            id="wj-002",
            name="ThermoBall Eco Jacket",
            brand="The North Face",
            price=149.99,
            original_price=199.00,
            shipping_eta="Arrives in 3–5 days",
            rating=4.5,
            review_count=1856,
            value_tag="Best value",
            description="Lightweight synthetic insulation that performs even when wet",
            why_recommended="Great warmth-to-price ratio with eco-friendly materials",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/thermoball-eco",
            category="winter_jackets",
            available_coupons=2,
            key_features=["Synthetic insulation", "Packable", "Eco-friendly", "Wet-weather performance"],
        ),
        Product(
            id="wj-003",
            name="Atom LT Hoody",
            brand="Arc'teryx",
            price=259.00,
            shipping_eta="Arrives in 1–2 days",
            rating=4.8,
            review_count=3102,
            value_tag="Premium pick",
            description="Versatile midlayer with Coreloft insulation for active use",
            why_recommended="Premium quality with excellent mobility — great for layering",
            source_name="Arc'teryx",
            source_url="https://arcteryx.com/atom-lt-hoody",
            category="winter_jackets",
            available_coupons=0,
            key_features=["Coreloft insulation", "Breathable", "Stretch panels", "Trim fit"],
        ),
        Product(
            id="wj-004",
            name="Wantdo Mountain Ski Jacket",
            brand="Wantdo",
            price=79.99,
            shipping_eta="Arrives in 4–6 days",
            rating=4.2,
            review_count=8923,
            value_tag="Budget pick",
            description="Windproof and waterproof winter jacket with fleece lining",
            why_recommended="Excellent budget option — warm enough for most winter conditions",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/wantdo-ski-jacket",
            category="winter_jackets",
            available_coupons=1,
            key_features=["Fleece lined", "Waterproof", "Multiple pockets", "Detachable hood"],
        ),
        Product(
            id="wj-005",
            name="Nano Puff Jacket",
            brand="Patagonia",
            price=199.00,
            shipping_eta="Arrives in 1–2 days",
            rating=4.6,
            review_count=4521,
            value_tag="Fastest shipping",
            description="Warm, windproof, and water-resistant with PrimaLoft insulation",
            why_recommended="Ships fastest with great all-around cold weather performance",
            source_name="Patagonia",
            source_url="https://www.patagonia.com/nano-puff-jacket",
            category="winter_jackets",
            available_coupons=0,
            key_features=["PrimaLoft Gold", "Fair Trade Certified", "Recycled materials", "Packable"],
        ),
    ],
    "monitors": [
        Product(
            id="mon-001",
            name='LG 27UK850-W 27" 4K UHD IPS Monitor',
            brand="LG",
            price=349.99,
            original_price=449.99,
            shipping_eta="Arrives in 2–4 days",
            rating=4.6,
            review_count=1923,
            value_tag="Best value",
            description="27-inch 4K UHD IPS display with USB-C connectivity and HDR10",
            why_recommended="Excellent color accuracy and value for home office work",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/lg-27uk850",
            category="monitors",
            available_coupons=1,
            key_features=["4K UHD", "USB-C", "HDR10", "IPS Panel", "Height adjustable"],
        ),
        Product(
            id="mon-002",
            name='Dell UltraSharp U2723QE 27"',
            brand="Dell",
            price=519.99,
            shipping_eta="Arrives in 1–2 days",
            rating=4.8,
            review_count=892,
            value_tag="Best overall",
            description="Premium 4K IPS Black panel with exceptional color accuracy",
            why_recommended="Industry-leading color accuracy — perfect for productivity",
            source_name="Dell",
            source_url="https://www.dell.com/ultrasharp-u2723qe",
            category="monitors",
            available_coupons=0,
            key_features=["IPS Black", "USB-C 90W", "KVM switch", "Factory calibrated"],
        ),
        Product(
            id="mon-003",
            name='ASUS ProArt PA278CV 27"',
            brand="ASUS",
            price=299.99,
            shipping_eta="Arrives in 3–5 days",
            rating=4.5,
            review_count=1456,
            value_tag="Budget pick",
            description="Calman-verified WQHD display for accurate color work",
            why_recommended="Professional color accuracy at a budget-friendly price",
            source_name="Best Buy",
            source_url="https://www.bestbuy.com/asus-proart-pa278cv",
            category="monitors",
            available_coupons=2,
            key_features=["WQHD", "USB-C 65W", "Calman verified", "100% sRGB"],
        ),
        Product(
            id="mon-004",
            name='Samsung Odyssey G7 32"',
            brand="Samsung",
            price=549.99,
            original_price=699.99,
            shipping_eta="Arrives in 1–2 days",
            rating=4.4,
            review_count=2341,
            value_tag="Fastest shipping",
            description="Curved QHD 240Hz gaming monitor with 1ms response time",
            why_recommended="Ships fastest — great if you game and work from home",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/samsung-odyssey-g7",
            category="monitors",
            available_coupons=1,
            key_features=["240Hz", "1ms response", "1000R curve", "QLED", "G-Sync compatible"],
        ),
    ],
    "headphones": [
        Product(
            id="hp-001",
            name="WH-1000XM5 Wireless",
            brand="Sony",
            price=348.00,
            original_price=399.99,
            shipping_eta="Arrives in 1–2 days",
            rating=4.7,
            review_count=5621,
            value_tag="Best overall",
            description="Industry-leading noise cancellation with exceptional sound quality",
            why_recommended="Best-in-class ANC with comfortable 30-hour battery life",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/sony-wh1000xm5",
            category="headphones",
            available_coupons=0,
            key_features=["30hr battery", "ANC", "Multipoint", "Speak-to-Chat"],
        ),
        Product(
            id="hp-002",
            name="AirPods Max",
            brand="Apple",
            price=449.00,
            shipping_eta="Arrives in 2–3 days",
            rating=4.5,
            review_count=3892,
            value_tag="Premium pick",
            description="Premium over-ear headphones with spatial audio and Apple ecosystem",
            why_recommended="Unmatched integration with Apple devices and premium build quality",
            source_name="Apple",
            source_url="https://www.apple.com/airpods-max",
            category="headphones",
            available_coupons=0,
            key_features=["Spatial Audio", "Apple H1 chip", "Digital Crown", "Aluminum build"],
        ),
        Product(
            id="hp-003",
            name="WH-1000XM4 Wireless",
            brand="Sony",
            price=228.00,
            original_price=349.99,
            shipping_eta="Arrives in 1–2 days",
            rating=4.7,
            review_count=9823,
            value_tag="Best value",
            description="Previous-gen flagship with still-excellent ANC and sound quality",
            why_recommended="Previous model at a steep discount — nearly as good as the XM5",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/sony-wh1000xm4",
            category="headphones",
            available_coupons=1,
            key_features=["30hr battery", "ANC", "LDAC", "Touch controls"],
        ),
        Product(
            id="hp-004",
            name="Soundcore Life Q35",
            brand="Anker",
            price=79.99,
            shipping_eta="Arrives in 2–4 days",
            rating=4.4,
            review_count=6721,
            value_tag="Budget pick",
            description="LDAC-supported ANC headphones at an unbeatable price",
            why_recommended="Best noise-cancelling headphones under $100",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/anker-q35",
            category="headphones",
            available_coupons=2,
            key_features=["40hr battery", "LDAC", "Hybrid ANC", "Comfortable fit"],
        ),
    ],
    "laptops": [
        Product(
            id="lap-001",
            name='MacBook Air 15" M3',
            brand="Apple",
            price=1299.00,
            shipping_eta="Arrives in 1–2 days",
            rating=4.8,
            review_count=2341,
            value_tag="Best overall",
            description="Thin and light with M3 chip, 18-hour battery, and stunning display",
            why_recommended="Best all-around laptop for most users — fast, light, and long-lasting",
            source_name="Apple",
            source_url="https://www.apple.com/macbook-air",
            category="laptops",
            available_coupons=0,
            key_features=["M3 chip", "18hr battery", '15.3" display', "Fanless design"],
        ),
        Product(
            id="lap-002",
            name="ThinkPad X1 Carbon Gen 11",
            brand="Lenovo",
            price=1149.00,
            original_price=1449.00,
            shipping_eta="Arrives in 3–5 days",
            rating=4.6,
            review_count=1567,
            value_tag="Best value",
            description="Legendary business laptop with Intel 13th-gen and all-day battery",
            why_recommended="Premium business laptop at a discount — excellent keyboard and build",
            source_name="Lenovo",
            source_url="https://www.lenovo.com/thinkpad-x1-carbon",
            category="laptops",
            available_coupons=1,
            key_features=["Intel i7-1365U", '14" 2.8K OLED', "1.12kg", "Fingerprint reader"],
        ),
        Product(
            id="lap-003",
            name="Aspire 5",
            brand="Acer",
            price=549.99,
            shipping_eta="Arrives in 2–4 days",
            rating=4.3,
            review_count=4521,
            value_tag="Budget pick",
            description="Reliable all-around laptop with Ryzen 7 and 16GB RAM",
            why_recommended="Best bang for your buck — handles everyday tasks with ease",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/acer-aspire-5",
            category="laptops",
            available_coupons=2,
            key_features=["Ryzen 7", "16GB RAM", "512GB SSD", '15.6" FHD'],
        ),
    ],
    "running_shoes": [
        Product(
            id="rs-001",
            name="Pegasus 41",
            brand="Nike",
            price=129.99,
            shipping_eta="Arrives in 2–3 days",
            rating=4.6,
            review_count=3456,
            value_tag="Best overall",
            description="Trusted daily trainer with React foam and responsive cushioning",
            why_recommended="The most versatile running shoe — great for daily training",
            source_name="Nike",
            source_url="https://www.nike.com/pegasus-41",
            category="running_shoes",
            available_coupons=0,
            key_features=["React foam", "Zoom Air", "Breathable mesh", "10mm drop"],
        ),
        Product(
            id="rs-002",
            name="Gel-Nimbus 26",
            brand="ASICS",
            price=159.95,
            shipping_eta="Arrives in 1–2 days",
            rating=4.7,
            review_count=2109,
            value_tag="Fastest shipping",
            description="Maximum cushioning for long runs with PureGEL technology",
            why_recommended="Best for long-distance comfort — ships the fastest",
            source_name="ASICS",
            source_url="https://www.asics.com/gel-nimbus-26",
            category="running_shoes",
            available_coupons=1,
            key_features=["PureGEL", "FF BLAST PLUS", "AHARPLUS outsole", "Neutral"],
        ),
        Product(
            id="rs-003",
            name="Ghost 15",
            brand="Brooks",
            price=99.95,
            original_price=139.95,
            shipping_eta="Arrives in 3–5 days",
            rating=4.5,
            review_count=7823,
            value_tag="Best value",
            description="Smooth, soft ride for everyday running with DNA LOFT cushioning",
            why_recommended="Previous model at a great discount — proven comfort and durability",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/brooks-ghost-15",
            category="running_shoes",
            available_coupons=2,
            key_features=["DNA LOFT", "Segmented crash pad", "Engineered mesh", "12mm drop"],
        ),
    ],
    "luggage": [
        Product(
            id="lg-001",
            name="The Carry-On",
            brand="Away",
            price=275.00,
            shipping_eta="Arrives in 3–5 days",
            rating=4.5,
            review_count=4521,
            value_tag="Best overall",
            description="Durable hardside carry-on with built-in USB charger and compression system",
            why_recommended="The gold standard for modern carry-on luggage",
            source_name="Away",
            source_url="https://www.awaytravel.com/carry-on",
            category="luggage",
            available_coupons=0,
            key_features=["TSA lock", "USB charger", "360° wheels", "Compression system"],
        ),
        Product(
            id="lg-002",
            name='Maxlite 5 21" Expandable Spinner',
            brand="Travelpro",
            price=119.99,
            original_price=159.99,
            shipping_eta="Arrives in 2–3 days",
            rating=4.4,
            review_count=6234,
            value_tag="Best value",
            description="Lightweight expandable spinner trusted by flight crews",
            why_recommended="Flight crew favorite at a great price — fits all budget airlines",
            source_name="Amazon",
            source_url="https://www.amazon.com/dp/travelpro-maxlite-5",
            category="luggage",
            available_coupons=1,
            key_features=["Expandable", "Lightweight 5.4lbs", "4-wheel spinner", "Water repellent"],
        ),
        Product(
            id="lg-003",
            name='Freeform 21" Carry-On Spinner',
            brand="Samsonite",
            price=149.99,
            shipping_eta="Arrives in 1–2 days",
            rating=4.6,
            review_count=3412,
            value_tag="Fastest shipping",
            description="Ultra-light polycarbonate hardside spinner with double wheels",
            why_recommended="Ships fastest with excellent durability and light weight",
            source_name="Samsonite",
            source_url="https://www.samsonite.com/freeform-21",
            category="luggage",
            available_coupons=0,
            key_features=["Polycarbonate shell", "Double wheels", "TSA lock", "Expandable"],
        ),
    ],
}


def get_mock_products(category: str) -> list[Product]:
    """Get mock products for a given category."""
    if category in MOCK_PRODUCTS:
        return MOCK_PRODUCTS[category]
    # Return a mix if category not found
    all_products = []
    for cat_products in MOCK_PRODUCTS.values():
        all_products.extend(cat_products[:2])
    return all_products[:5]
